ci:
  autofix_prs: true
  autofix_commit_msg: "chore: auto fixes from pre-commit"
  autofix_prs_limit: 5
  autoupdate_schedule: monthly
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  skip: []
